# SPDX-License-Identifier: BSD-2-Clause

PACKAGE=	tests

TESTSDIR=	${TESTSBASE}/sys/geom/class/${.CURDIR:T}

ATF_TESTS_SH+=	hibernate_test

${PACKAGE}FILES+=	no-mutation-check.sh
${PACKAGE}FILES+=	source-contract-check.sh

.include <bsd.test.mk>
